### PR TITLE
Fix path issues

### PR DESCRIPTION
**Pull request by ghost**
I think this fixes Issue #4 @wlbragg

### CODE REVIEW

**Comment by wlbragg** [comment]
@D-ECHO Your a genius. You know how many time I have looked for this. It appears the "flight-recorder" path was the issue.
I got it to populate correctly just by fixing the flight-recorder path.

Did you also need to remove the "crash" loading to get it to populate or is that something else?

In all the time I've been working on the AirCrane I don't think I ever looked closely at load-unload.xml and was wondering where the crash logic was. I'm sure at some point I will change some things in it as it just kills the simulation. At the very least I would like to be able to reset it so you don't have to reload the entire system.

**Comment by ghost** [comment]
@wlbragg I had removed the load-unload inclusion as I could not find this file anywhere, if you tell me where it is I can put it back in :) And thanks!

**Comment by wlbragg** [comment]
My mistake, this load-unload.xml was the "disintegration" code used on another aircraft I was playing around with locally. I never uploaded the supporting files to git. We should leave it out for now. Good catch, thanks. I'll merge as is.

**Comment by ghost** [comment]
Welcome :)

**Pull request merged**
